### ISSUE TITLE
Bug: Adding icon by Iconize/Iconic plugin showing icon in top of the title instead of before the title.

### ISSUE THREAD

**Issue by ZeroMB** [xhuajin/obsidian-file-preview#20]
![IMG_20250108_130412](https://github.com/user-attachments/assets/514c60a3-05cf-4580-ae24-6cccfbd9ad9a)

**Comment by xhuajin** [comment]
Iconic pllugin has been adapted, you can try 1.1.4.

**Comment by ZeroMB** [comment]
Fixed!

**Comment by rudironsoni** [comment]
This is not fixed. I'm using File Preview 1.1.3 and Iconic 1.1.4 but I'm getting this:

<img width="800" height="612" alt="Image" src="https://github.com/user-attachments/assets/6497106b-daed-4fef-bab9-73cfc09e076b" />

**Comment by ZeroMB** [comment]
Download from GitHub, not Obsidian store. Latest version available on GitHub.

**Comment by rudironsoni** [comment]
> Download from GitHub, not Obsidian store. Latest version available on GitHub.

it worked, thanks!
